package UI;

import BLL.GestionMatricula;
import Pachacama.Util;
import java.io.IOException;
import javax.swing.JOptionPane;

public class frmRegistroCalificaciones extends javax.swing.JInternalFrame {

    private final String titulo = "Registro de Calificaciones";
    private GestionMatricula matriculaBll = new GestionMatricula();

    private void consultarMatricula() throws IOException {
        String numero = this.txtNumeroMatricula.getText();
        matriculaBll.consultar(numero);
        this.txtDatosMatricula.setText(matriculaBll.imrpimir());
    }

    private boolean validar() {
        float nota = (float) this.snnValor.getValue();
        if (nota == 0.f) {
            vtnPrincipal.verMensaje("Calificacion no Valida", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private String calificar() throws IOException {
        float nota = (float) this.snnValor.getValue();
        String mensaje = matriculaBll.calificar(nota);
        matriculaBll.archivar();
        return mensaje;
    }

    public frmRegistroCalificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroCalificacion = new javax.swing.JPanel();
        lblNumeroMatricula = new javax.swing.JLabel();
        txtNumeroMatricula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlDatosMatricula = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatosMatricula = new javax.swing.JTextArea();
        pnlCalificacion = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        snnValor = new javax.swing.JSpinner();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro de Calificaciones");

        pnlRegistroCalificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Calificaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 3, 18))); // NOI18N

        lblNumeroMatricula.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        lblNumeroMatricula.setText("N° Matricula:");

        txtNumeroMatricula.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("/home/labctr/Documentos/Programacion II/iconos/search.png")); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        pnlDatosMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de la Matrícula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 3, 15))); // NOI18N

        txtDatosMatricula.setEditable(false);
        txtDatosMatricula.setColumns(20);
        txtDatosMatricula.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        txtDatosMatricula.setRows(5);
        txtDatosMatricula.setEnabled(false);
        jScrollPane1.setViewportView(txtDatosMatricula);

        javax.swing.GroupLayout pnlDatosMatriculaLayout = new javax.swing.GroupLayout(pnlDatosMatricula);
        pnlDatosMatricula.setLayout(pnlDatosMatriculaLayout);
        pnlDatosMatriculaLayout.setHorizontalGroup(
            pnlDatosMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlDatosMatriculaLayout.setVerticalGroup(
            pnlDatosMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosMatriculaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCalificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Calificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 3, 15))); // NOI18N

        lblValor.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        lblValor.setText("Valor:");

        snnValor.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        snnValor.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(14.02f), Float.valueOf(0.01f), Float.valueOf(20.0f), Float.valueOf(0.01f)));
        snnValor.setToolTipText("Formato ##,##");

        javax.swing.GroupLayout pnlCalificacionLayout = new javax.swing.GroupLayout(pnlCalificacion);
        pnlCalificacion.setLayout(pnlCalificacionLayout);
        pnlCalificacionLayout.setHorizontalGroup(
            pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        pnlCalificacionLayout.setVerticalGroup(
            pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(snnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblValor))
        );

        btnGuardar.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("/home/labctr/Documentos/Programacion II/iconos/save.png")); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroCalificacionLayout = new javax.swing.GroupLayout(pnlRegistroCalificacion);
        pnlRegistroCalificacion.setLayout(pnlRegistroCalificacionLayout);
        pnlRegistroCalificacionLayout.setHorizontalGroup(
            pnlRegistroCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroCalificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlRegistroCalificacionLayout.createSequentialGroup()
                        .addComponent(lblNumeroMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addComponent(pnlCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroCalificacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        pnlRegistroCalificacionLayout.setVerticalGroup(
            pnlRegistroCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroCalificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRegistroCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroMatricula)
                        .addComponent(txtNumeroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistroCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistroCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (validar()) {
                String mensaje = this.calificar();
                vtnPrincipal.verMensaje(mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            Util.imprimir("ERROR. " + e.toString());
            vtnPrincipal.verMensaje("Error al Calificar la Matrícula", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            this.consultarMatricula();
        } catch (Exception e) {
            Util.imprimir("ERROR. " + e.toString());
            vtnPrincipal.verMensaje("Error al Buscar la Matrícula", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroMatricula;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlCalificacion;
    private javax.swing.JPanel pnlDatosMatricula;
    private javax.swing.JPanel pnlRegistroCalificacion;
    private javax.swing.JSpinner snnValor;
    private javax.swing.JTextArea txtDatosMatricula;
    private javax.swing.JTextField txtNumeroMatricula;
    // End of variables declaration//GEN-END:variables
}
