package UI;

import BEU.Estudiante;
import BLL.GestionEstudiante;
import Pachacama.Util;
import java.io.IOException;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class frmRegistroEstudiante extends javax.swing.JInternalFrame {

    private final String titulo = "Registro del Estudiante";
    private GestionEstudiante estudianteBll = new GestionEstudiante();

    private void iniciarListado() throws IOException {
        estudianteBll.leerEstudiantes();
    }

    private String verificarClub(JCheckBox chk) {
        if (chk.isSelected()) {
            return chk.getText();
        }
        return "";
    }

    private void crearEstudiante() {
        Estudiante nuevo = new Estudiante();
        nuevo.setCedula(txtCedula.getText());
        nuevo.setNombre(this.txtNombre.getText());
        nuevo.setApellido(this.txtApellido.getText());
        nuevo.setCarrera(this.cmbCarrera.getSelectedItem().toString());
        nuevo.addClub(this.verificarClub(chkDanza));
        nuevo.addClub(this.verificarClub(chkAjedrez));
        nuevo.addClub(this.verificarClub(chkAndinismo));
        nuevo.addClub(this.verificarClub(chkBasket));
        nuevo.addClub(this.verificarClub(chkFutbol));
        nuevo.addClub(this.verificarClub(chkMusica));
        nuevo.addClub(this.verificarClub(chkRobotica));
        nuevo.addClub(this.verificarClub(chkTenis));
        estudianteBll.getEstudiantes().add(nuevo);
    }

    private void archivar() throws IOException {
        estudianteBll.archivar();
    }

    public frmRegistroEstudiante() {
        initComponents();
        try {
            iniciarListado();
        } catch (IOException e) {
            Util.imprimir(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        pnlDatosextracurricurales = new javax.swing.JPanel();
        chkDanza = new javax.swing.JCheckBox();
        chkRobotica = new javax.swing.JCheckBox();
        chkMusica = new javax.swing.JCheckBox();
        chkAndinismo = new javax.swing.JCheckBox();
        chkFutbol = new javax.swing.JCheckBox();
        chkAjedrez = new javax.swing.JCheckBox();
        chkTenis = new javax.swing.JCheckBox();
        chkBasket = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro de Estudiante");

        pnlRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 3, 18))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 3, 18))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        lblNombre.setText("Nombres:");

        txtNombre.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N

        lblApellido.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        lblApellido.setText("Apellidos:");

        txtApellido.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N

        lblCedula.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        lblCedula.setText("Cedula:");

        txtCedula.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedula)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addComponent(txtApellido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pnlDatosextracurricurales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Extracurricurales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 3, 18))); // NOI18N

        chkDanza.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkDanza.setText("Club de Danza");

        chkRobotica.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkRobotica.setText("Club de Robotica");

        chkMusica.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkMusica.setText("Club de Música");

        chkAndinismo.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkAndinismo.setText("Club de Andinismo");

        chkFutbol.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkFutbol.setText("Club de Futbol");

        chkAjedrez.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkAjedrez.setText("Club de Ajedrez");

        chkTenis.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkTenis.setText("Club de Tenis");

        chkBasket.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        chkBasket.setText("Club de Basket");

        javax.swing.GroupLayout pnlDatosextracurricuralesLayout = new javax.swing.GroupLayout(pnlDatosextracurricurales);
        pnlDatosextracurricurales.setLayout(pnlDatosextracurricuralesLayout);
        pnlDatosextracurricuralesLayout.setHorizontalGroup(
            pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosextracurricuralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosextracurricuralesLayout.createSequentialGroup()
                        .addComponent(chkAndinismo)
                        .addGap(18, 18, 18)
                        .addComponent(chkBasket))
                    .addGroup(pnlDatosextracurricuralesLayout.createSequentialGroup()
                        .addGroup(pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDanza)
                            .addComponent(chkRobotica)
                            .addComponent(chkMusica))
                        .addGap(26, 26, 26)
                        .addGroup(pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTenis)
                            .addComponent(chkAjedrez)
                            .addComponent(chkFutbol))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosextracurricuralesLayout.setVerticalGroup(
            pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosextracurricuralesLayout.createSequentialGroup()
                .addGroup(pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDanza)
                    .addComponent(chkFutbol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkRobotica)
                    .addComponent(chkAjedrez))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMusica)
                    .addComponent(chkTenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosextracurricuralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAndinismo)
                    .addComponent(chkBasket))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnGuardar.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("/home/labctr/Documentos/Programacion II/iconos/save.png")); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Academicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 3, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        jLabel1.setText("Carrera:");

        cmbCarrera.setFont(new java.awt.Font("Ubuntu Condensed", 3, 15)); // NOI18N
        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería de Software", "Ingeniería Electronica", "Ingeniería Electromecanica", "Ingeniería Mecatrónica", "Ingeniería Petroquimica" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlDatosextracurricurales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosextracurricurales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            crearEstudiante();
            archivar();
            vtnPrincipal.verMensaje("Estudiante agregado Exitosamente", titulo, JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            Util.imprimir("ERROR. " + e.toString());
            vtnPrincipal.verMensaje("Error al Guardar el Estudiante", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkAjedrez;
    private javax.swing.JCheckBox chkAndinismo;
    private javax.swing.JCheckBox chkBasket;
    private javax.swing.JCheckBox chkDanza;
    private javax.swing.JCheckBox chkFutbol;
    private javax.swing.JCheckBox chkMusica;
    private javax.swing.JCheckBox chkRobotica;
    private javax.swing.JCheckBox chkTenis;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlDatosextracurricurales;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
